spring:
  rabbitmq:
    username: user
    password: password
    host: 192.168.99.100
    port: 5672
  profiles:
    active: tut2,sender

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000